USE [master]
GO
CREATE LOGIN [APPLICATION_NAME] WITH PASSWORD=N'APPLICATION_PASSWORD', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
USE [APPLICATION_DATABASE_NAME]
GO
CREATE USER [APPLICATION_NAME] FOR LOGIN [APPLICATION_NAME]
GO
USE [APPLICATION_DATABASE_NAME]
GO
ALTER ROLE [db_owner] ADD MEMBER [APPLICATION_NAME]
GO
